# book-catalog deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: sevenpointtworegistry.azurecr.io/book-catalog:latest  # Updated image URL
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "postgresql://sevenpointtwo_user:mfFYxjpW6gP1FG2CXw7yaT9FxY4uyvLQ@dpg-crt8hmtumphs73fke9f0-a.oregon-postgres.render.com/sevenpointtwo"

---
# inventory-management deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: sevenpointtworegistry.azurecr.io/inventory-management:latest  # Updated image URL
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "postgresql://sevenpointtwo_user:mfFYxjpW6gP1FG2CXw7yaT9FxY4uyvLQ@dpg-crt8hmtumphs73fke9f0-a.oregon-postgres.render.com/sevenpointtwo"
